apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  annotations:
    version: 1.0.0
spec:
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Values.name }}
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      securityContext: {}
      terminationGracePeriodSeconds: 30
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.artifactRegistry }}{{ .Values.name }}:{{ .Values.version }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBIT_SVC_IP_PORT
              value: {{ .Values.rabbitSvcIpPort }}
            - name: RABBIT_USERNAME
              value: {{ .Values.rabbitUsername }}
            - name: RABBIT_PASSWORD
              value: {{ .Values.rabbitPassword }}
            - name: QUEUE_NAME
              value: {{ .Values.queueName }}
          # ports:
          #   - containerPort: 8080
          #     protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 1G
            requests:
              cpu: 200m
              memory: 500M
