apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: consumer-app-scaled-object
spec:
  scaleTargetRef:
    kind: Deployment
    name: consumer-deployment
  pollingInterval: 5
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
    - type: rabbitmq
      metadata:
        metricName: my.queue.1-metrics
        host: amqp://default_user_ktZcW6F9CIxdu12bjeh:634-PTb6kfIQkV_1xkW7BIssJeybNqfA@10.96.103.197:5672
        protocol: auto
        mode: QueueLength # QueueLength | MessageRate
        value: "200"
        activationValue: "10"
        queueName: my.queue.1
        vhostName: /
